sudo: required

language: go

services:
  - docker

script:
  - go get github.com/elastic/beats
  - (cd $GOPATH/src/github.com/elastic/beats && git checkout 5.2)
  - make
  - make test
  - make acceptance-test
